apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoApplications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/araminian/argo-repos.git
    targetRevision: HEAD
    path: manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd